sudo: false
language: node_js
node_js:
- '4'
install:
- npm install
- npm run build
script:
- npm run lint
- npm test
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy:static'
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: b9I6JKo6cTPyEOssg8Vyqi0bXOzFfPPo9SAAmmjg71oLcvQl8s2/ruNNiWWByUm64YCAUNAq4hChOcVrNkSadw6HxAwej0TNItNDbh7Gsxtt0kqWDk4Q366eVqMBvWaOpCUQ8MTzGOXZmcifynADjEkESXJIxkgAVsqA1j1Ak/MTxxvea0V9drcttS9peN/yxhcIaMIv0MiQnvP7ieLBzv6UhHegVVi59Fv6HYBxvJz3Q9jdL5cpxbgPNf9gccisONTRf1IB66TEWVVyixtnSh0yGh9cUg8QEgXMHhHF25zVRZHXvvIE2w+mbIMVM6rDVM2Tzan+uMNZfMapl+Kp+G+2gf+a/aCQUrstnsAnkON9yaBKfxngBtRkGaFdjUB1Pyx5JINLSAO8IkXFahZNa/MrefQrXHlqM92rhrWpDEiDDorKbHORlBdIz8vPTuxqonHEqIduGPpdyshrIGyo29D3+RF1T1EHO59u1MkCvKCFMmM4qlo0ifsQhUwioBV+hPP90mK05a5/dX9vr6WGDo/QmiRN6g+kL+QIu6xlaQcN6boVYqpQm6TtiWkg0gLIZCGBYPAYzDIStQN+54LhArmrFIE8UfrcN0FDmD11gz/ABnEYfQs0wZfF8xUEenvI+r+ukiEdZ2VtlAXAXB70Vy6+YwWugY+4p1O4OuWkKNs=
  on: master
  app: urfu2015-notes
